# Generated by Django 5.2.8 on 2025-12-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, unique=True, verbose_name='使用者名稱')),
                ('hashed_password', models.TextField(verbose_name='雜湊密碼')),
            ],
            options={
                'verbose_name': '使用者',
                'verbose_name_plural': '使用者',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=255, unique=True, verbose_name='工作名稱')),
            ],
            options={
                'verbose_name': '工作',
                'verbose_name_plural': '工作',
                'db_table': 'work',
            },
        ),
    ]
