# myapp/models.py
from django.db import models

class User(models.Model):
    """
    對應 SQL 表：
    CREATE TABLE IF NOT EXISTS "user" (
        "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
        "user_name" VARCHAR(255) NOT NULL UNIQUE,
        "hashed_password" TEXT NOT NULL,
        PRIMARY KEY("id")
    );
    """
    
    # Django 會自動創建一個 auto-increment 的 'id' Primary Key 欄位。
    
    user_name = models.CharField(
        max_length=255, 
        unique=True, 
        verbose_name='使用者名稱'
    )
    
    hashed_password = models.TextField(
        verbose_name='雜湊密碼'
    )

    class Meta:
        # 設置資料庫表名為 "user"
        db_table = 'user' 
        verbose_name = '使用者'
        verbose_name_plural = '使用者'
        
    def __str__(self):
        return self.user_name

class Work(models.Model):
    """
    對應 SQL 表：
    CREATE TABLE IF NOT EXISTS "work" (
        "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
        "work_name" VARCHAR(255) NOT NULL UNIQUE,
        PRIMARY KEY("id")
    );
    """

    work_name = models.CharField(
        max_length=255, 
        unique=True, 
        verbose_name='工作名稱'
    )

    class Meta:
        # 設置資料庫表名為 "work"
        db_table = 'work' 
        verbose_name = '工作'
        verbose_name_plural = '工作'

    def __str__(self):
        return self.work_name